### ISSUE TITLE
Allow to create pre-configure the filter by query string

### ISSUE THREAD

**Issue by Simply007** [Kentico/ems-extension-marketplace#3]
### Motivation

It would be great to be able to set the initial filter setting by the query string.
* search phrase 
* category

### Proposed solution

Load the [qs](https://www.npmjs.com/package/qs) npm package and load the value to the initial state of the filter.

* search phrase = query string : s=dasjhfladfs
* category (multiply - split by ´;´ char) category=mvc%20widget;mvc%20section

### Additional context

It would allow sharing the links to the specific items or the item categories.

**Comment by MSharifi78** [comment]
I'm on it :)

**Comment by Simply007** [comment]
Hello @MSharifi78 - great to hear that! I have assigned you the issue so that everybody knows that this issue is taken.

If you have any questions, feel free to ask!
