### ISSUE TITLE
Alphabetical items ordering

### ISSUE THREAD

**Issue by makma** [Kentico/ems-extension-marketplace#36]
### Motivation

After the pull request #35 is merged, there will be items in the listing in random order. Implement Alphabetical order (A -> Z; Z->A) using the dropdown selector similar to the Kentico versions dropdown.

### Proposed solution

Alphabetical ordering using the dropdown selector similar to the Kentico versions dropdown.

**Comment by PedroL33** [comment]
Can I take a shot at this?

**Comment by Simply007** [comment]
Hello @PedroL33,

sure - I have assigned you this issue. 
Good luck and looking forward to the pull request!

**Comment by PedroL33** [comment]
Hey thanks for the assignment.

I have a question.

Did you want an option to remove alphabetical ordering?  And if so would you want it to reshuffle or revert back to the original shuffle.  

Thanks for the help!

**Comment by Simply007** [comment]
I would add a second selector like the one that is for version and set the default to "Random sort" and make a second option "Alphabetical sort/"(A -> Z)".

![image](https://user-images.githubusercontent.com/9218736/84473523-8203b700-ac89-11ea-87aa-e57d798f4fa8.png)

@makma 
- Do you also want then reverse alphabetical sort? (Z ->A)
- Are you OK with the labels?

**Comment by PedroL33** [comment]
Pull request made has been made.

**Comment by makma** [comment]
Hey guys!
Both (ASC and DESC) orderings already are in the PR.
I believe [A -Z] and [Z - A] ordering naming is explanatory enough (suggested in PR code review).

PR review is in progress.
