### ISSUE TITLE
Set descending order in version filter

### ISSUE THREAD

**Issue by Simply007** [Kentico/ems-extension-marketplace#7]
### Motivation

In most of the cases when users want to filter by the version, they want to select the latest version.
Descending order in the version selector would make this task a little bit easier.

### Proposed solution

Adjust the version initializing in the https://github.com/Kentico/ems-extension-marketplace/blob/master/src/utils/kenticoVersions.ts#L19 to use descending order.

**Comment by MisaelMa** [comment]
How can I run the tests to upload the solution?

**Comment by makma** [comment]
Hi @MisaelMa ,there is just one test and build CI configuration which runs with every commit/pull request.
